### ISSUE TITLE
Thanks for developing this package 

### ISSUE THREAD

**Issue by payam-zahedi** [NavidShokoufeh/v2ray#2]
V2RAY is a service that is very necessary in our daily life in Iran. 

So as a member of Persian flutter community I want to let you know that we are supporting you. 

If you need help on developing or maintaining this package, you can count on us.

https://t.me/persian_flutter

https://t.me/payamzahedi95

**Comment by NavidShokoufeh** [comment]
Thanks for your support, it's my pleasure to to help our community. 
I'm doing my best to publish as soon as possible.
